// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlI-6OnKnq5zQMawRVZtQRPXLVI9Y83k',
    appId: '1:177724858605:web:e047c9de146a2f416b6ce4',
    messagingSenderId: '177724858605',
    projectId: 'ocall-7fc83',
    authDomain: 'ocall-7fc83.firebaseapp.com',
    storageBucket: 'ocall-7fc83.appspot.com',
    measurementId: 'G-8Y0VK9FMND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQxdyUDGqEh60zHsubGos5v3nBLG_KLs',
    appId: '1:177724858605:android:71cf9f32a4893b4d6b6ce4',
    messagingSenderId: '177724858605',
    projectId: 'ocall-7fc83',
    storageBucket: 'ocall-7fc83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrsqJ6J3DyFehmoaTzJyIydEBxVVU31QY',
    appId: '1:177724858605:ios:3e90a7c1d1d07f4e6b6ce4',
    messagingSenderId: '177724858605',
    projectId: 'ocall-7fc83',
    storageBucket: 'ocall-7fc83.appspot.com',
    iosClientId: '177724858605-9unnel153ih0o60o22m3delacdc4n41s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrsqJ6J3DyFehmoaTzJyIydEBxVVU31QY',
    appId: '1:177724858605:ios:3e90a7c1d1d07f4e6b6ce4',
    messagingSenderId: '177724858605',
    projectId: 'ocall-7fc83',
    storageBucket: 'ocall-7fc83.appspot.com',
    iosClientId: '177724858605-9unnel153ih0o60o22m3delacdc4n41s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocallApp',
  );
}
